import { stringify, parse } from "yaml";
import { readFile, writeFile } from "node:fs/promises";
import type { PersonaFile } from "../schema/persona.js";
import { validatePersonaFile } from "../schema/persona.js";

/**
 * YAML Serialisation Utilities
 *
 * Handles reading and writing persona files in YAML format.
 * YAML is the canonical storage format because it is:
 * - human-readable and editable
 * - diffable in version control
 * - supports comments (for interpretive notes)
 */

/**
 * Serialise a PersonaFile to YAML string.
 */
export function personaToYaml(persona: PersonaFile): string {
  const header = [
    "# Persona Definition File",
    `# ${persona.metadata.name}`,
    `# Version: ${persona.metadata.version}`,
    `# Last updated: ${persona.metadata.last_updated}`,
    `# Generated by: Persona-x`,
    "",
  ].join("\n");

  return header + stringify(persona, { lineWidth: 100 });
}

/**
 * Parse a YAML string into a PersonaFile.
 * Validates against the schema after parsing.
 */
export function yamlToPersona(yamlContent: string): {
  success: boolean;
  data?: PersonaFile;
  errors?: string[];
} {
  let parsed: unknown;
  try {
    parsed = parse(yamlContent);
  } catch (err) {
    return { success: false, errors: [`YAML parse error: ${String(err)}`] };
  }

  const result = validatePersonaFile(parsed);
  if (result.success && result.data) {
    return { success: true, data: result.data };
  }

  const errors =
    result.errors?.issues.map(
      (issue: { path: (string | number)[]; message: string }) => `${issue.path.join(".")}: ${issue.message}`
    ) ?? ["Unknown validation error"];

  return { success: false, errors };
}

/**
 * Read a persona file from disk.
 */
export async function readPersonaFile(
  filePath: string
): Promise<{ success: boolean; data?: PersonaFile; errors?: string[] }> {
  try {
    const content = await readFile(filePath, "utf-8");
    return yamlToPersona(content);
  } catch (err) {
    return {
      success: false,
      errors: [`Failed to read ${filePath}: ${String(err)}`],
    };
  }
}

/**
 * Write a persona file to disk as YAML.
 */
export async function writePersonaFile(
  filePath: string,
  persona: PersonaFile
): Promise<void> {
  const yaml = personaToYaml(persona);
  await writeFile(filePath, yaml, "utf-8");
}
